#!/bin/bash

loop_count=0
is_running="running"

for (( ; ; ))
do
  ((loop_count=loop_count+1))

  service_status=$(sudo systemctl status rippled.service | grep "Active:")

#  echo -e "\n✅✅✅ Docker IP ✅✅✅"
#  podman_ip=$(podman inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' rippled)

#  echo -e "\n✅✅✅ Checking ledger status ✅✅✅"
  rippled_ledger=$(sudo /opt/ripple/bin/rippled server_info | grep "complete_ledgers")

  echo -e "✅✅✅ Status Report ✅✅✅"
  echo -e "🐳 Service Status ⏩ $service_status"
#  echo -e "🐳 Docker IP ⏩ $podman_ip"
  echo -e "🌊 Rippled Ledgers ⏩ $rippled_ledger" | xargs

  if [[ "$service_status" != *"$is_running"* ]]; then
    echo -e "\nService Not Running, exiting..."
    break
  fi

  echo -e "\nSleeping 60s. NOTE: Infinite loop (#$loop_count) [hit CTRL+C to stop]\n😴"
  sleep 60
done

