#!/bin/bash

self(){
  DIR=$( cd "$( dirname "$0" )/" && pwd)
  echo $DIR
}

echo "Stopping containers"
podman ps -a|grep xrpllabsofficial/xrpld:latest|cut -d " " -f 1 |xargs -I___ podman stop ___

if [[ $(podman images -a|grep xrpllabsofficial/xrpld:latest|wc -l) -gt "0" ]]; then
  echo "Removing image"
  podman rmi -f xrpllabsofficial/xrpld:latest
fi

echo "Building image"
podman build --tag xrpllabsofficial/xrpld:latest $(self)/../.

echo "Done, you can now run $(self)/up"
