#!/bin/bash

self(){
  DIR=$( cd "$( dirname "$0" )/" && pwd)
  echo $DIR
}

$(self)/down

PORT=80

CUSTOMPORT=$(echo $1|egrep "^[0-9]+$"|wc -l)

if [[ "$CUSTOMPORT" -gt "0" ]]; then
    PORT=$1
fi

podman run \
    -dit \
    --name rippled \
    --label rippled=true \
    -p 5005:5005 \
    -p 51234:51234 \
    -p 51235:51235 \
    -v $(self)/../config:/config/ \
    xrpllabsofficial/xrpld:latest

podman logs -f rippled
